# Generated by Django 3.2.18 on 2025-03-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20250325_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringexpense',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
